# Script to update all commit messages with detailed descriptions from README

Set-Location "c:\1deathcounter"

# Map of file paths to their detailed descriptions
$fileDescriptions = @{
    "DeathCounterInstaller.exe" = "Latest installer executable (v1.5). This is the main file users should download. Uses Git LFS for large file storage. Includes Python version compatibility checking and automatic Japanese language pack download for Sekiro support."
    "README.md" = "This documentation file. Contains installation instructions, feature descriptions, repository structure, and troubleshooting information."
    ".gitattributes" = "Git LFS configuration file. It tells Git which large files (e.g., `*.exe`) should be tracked by Git Large File Storage instead of directly in the Git repository. This prevents repository bloat and allows for easier management of large binaries."
    ".gitignore" = "Git ignore rules. This file specifies intentionally untracked files that Git should ignore (e.g., temporary files, build artifacts, local configurations). It helps keep the repository clean and focused on source code."
    "cleanup_github_repo.ps1" = "Utility PowerShell script used to organize the repository structure, remove old files, and copy the desired folder layout from a local reference folder. Helps maintain consistency between local development and GitHub repository."
    "create_release.ps1" = "PowerShell script for creating GitHub releases. Can be used to automate the process of creating a new release with the installer executable as a downloadable asset."
    
    # All Contents/ folder files
    "All Contents/multi_game_death_counter.py" = "Main daemon script that performs screen capture, OCR detection, and death counting"
    "All Contents/death_counter_gui.py" = "GUI application for controlling the daemon and viewing death statistics"
    "All Contents/games_config.json" = "Configuration file defining game-specific settings (capture regions, keywords, process names)"
    "All Contents/switch_game_manual.py" = "Script for manually switching between games"
    "All Contents/change_monitor_id.py" = "Utility for changing monitor detection settings"
    "All Contents/capture_debug_once.py" = "Debug utility for capturing a single screen region for testing"
    "All Contents/reset_death_counter.py" = "Script to reset death counts to zero"
    "All Contents/test_daemon_start.py" = "Test script to diagnose daemon startup issues"
    "All Contents/deathcounteraction.cs" = "Streamer.bot action file for integration"
    
    # All Contents/ batch files
    "All Contents/START_DEATH_COUNTER.bat" = "Batch file for starting the daemon"
    "All Contents/STOP_DEATH_COUNTER.bat" = "Batch file for stopping the daemon"
    "All Contents/RESET_DEATH_COUNTER.bat" = "Batch file for resetting death counts"
    "All Contents/CAPTURE_DEBUG.bat" = "Batch file for running debug capture"
    "All Contents/CHANGE_MONITOR_ID.bat" = "Batch file for changing monitor settings"
    "All Contents/install_dependencies.bat" = "Batch file for installing Python dependencies"
    
    # All Contents/ other files
    "All Contents/total_deaths.txt" = "Text file storing total death counts"
    "All Contents/daemon.ready" = "Flag file indicating daemon is ready"
    "All Contents/daemon_startup_error.txt" = "Text file containing daemon startup errors"
    
    # Debug.Test/ files
    "Debug.Test/capture_debug_once.py" = "Debug utility for capturing a single screen region for testing"
    "Debug.Test/test_daemon_start.py" = "Test script to diagnose daemon startup issues"
    "Debug.Test/CAPTURE_DEBUG.bat" = "Batch file for running debug capture"
    
    # Edit/ files
    "Edit/build_single_file.py" = "Build script that packages all application files into a single installer script. This script embeds all necessary files (Python scripts, configs, batch files) into DeathCounter_Installer_Standalone.py."
    "Edit/DeathCounter_Installer_Standalone.py" = "The standalone installer script generated by build_single_file.py. This is the Python script version of the installer before it's compiled into an .exe using PyInstaller."
    "Edit/multi_game_death_counter.py" = "Source copy of main daemon script (for reference during build process)"
    "Edit/death_counter_gui.py" = "Source copy of GUI application (for reference during build process)"
    "Edit/games_config.json" = "Source copy of configuration file (for reference during build process)"
    "Edit/switch_game_manual.py" = "Source copy of game switching script (for reference during build process)"
    "Edit/change_monitor_id.py" = "Source copy of monitor utility (for reference during build process)"
    "Edit/capture_debug_once.py" = "Source copy of debug utility (for reference during build process)"
    "Edit/reset_death_counter.py" = "Source copy of reset script (for reference during build process)"
    "Edit/test_daemon_start.py" = "Source copy of test script (for reference during build process)"
    "Edit/deathcounteraction.cs" = "Source copy of Streamer.bot action file (for reference during build process)"
    "Edit/START_DEATH_COUNTER.bat" = "Source copy of start batch file (for reference during build process)"
    "Edit/STOP_DEATH_COUNTER.bat" = "Source copy of stop batch file (for reference during build process)"
    "Edit/RESET_DEATH_COUNTER.bat" = "Source copy of reset batch file (for reference during build process)"
    "Edit/CAPTURE_DEBUG.bat" = "Source copy of debug batch file (for reference during build process)"
    "Edit/CHANGE_MONITOR_ID.bat" = "Source copy of monitor batch file (for reference during build process)"
    "Edit/install_dependencies.bat" = "Source copy of install batch file (for reference during build process)"
}

# Function to get description for a file
function Get-FileDescription {
    param($filePath)
    
    $relativePath = $filePath.Replace("c:\1deathcounter\", "").Replace("\", "/")
    
    # Check for exact match
    if ($fileDescriptions.ContainsKey($relativePath)) {
        return $fileDescriptions[$relativePath]
    }
    
    # Check for folder-based descriptions
    if ($relativePath -like "All Contents/*") {
        $fileName = Split-Path $relativePath -Leaf
        $ext = [System.IO.Path]::GetExtension($fileName).ToLower()
        $name = [System.IO.Path]::GetFileNameWithoutExtension($fileName)
        
        switch ($ext) {
            ".py" { return "Python script in All Contents folder: $name" }
            ".bat" { return "Batch file in All Contents folder: $name" }
            ".json" { return "Configuration file in All Contents folder: $name" }
            ".txt" { return "Text file in All Contents folder: $name" }
            ".cs" { return "C# file in All Contents folder: $name" }
            default { return "File in All Contents folder: $fileName" }
        }
    }
    
    if ($relativePath -like "Debug.Test/*") {
        $fileName = Split-Path $relativePath -Leaf
        $ext = [System.IO.Path]::GetExtension($fileName).ToLower()
        $name = [System.IO.Path]::GetFileNameWithoutExtension($fileName)
        
        switch ($ext) {
            ".py" { return "Debug and testing utility: $name" }
            ".bat" { return "Debug and testing batch file: $name" }
            default { return "Debug and testing file: $fileName" }
        }
    }
    
    if ($relativePath -like "Edit/*") {
        $fileName = Split-Path $relativePath -Leaf
        $ext = [System.IO.Path]::GetExtension($fileName).ToLower()
        $name = [System.IO.Path]::GetFileNameWithoutExtension($fileName)
        
        switch ($ext) {
            ".py" { return "Development script: $name" }
            ".bat" { return "Development batch file: $name" }
            ".json" { return "Development configuration file: $name" }
            ".cs" { return "Development C# file: $name" }
            default { return "Development file: $fileName" }
        }
    }
    
    # Default
    return $relativePath
}

Write-Host "Creating filter-branch script to update all commit messages..."
Write-Host ""

# Get all commits
$commits = git log --format="%H %s" --all

# Create a filter script that will update commit messages based on changed files
$filterScript = @'
#!/bin/sh
commit_hash="$GIT_COMMIT"
commit_msg=$(cat)

# Get list of files changed in this commit
files=$(git diff-tree --no-commit-id --name-only -r "$commit_hash" 2>/dev/null)

if [ -z "$files" ]; then
    echo "$commit_msg"
    exit 0
fi

# Get the first file changed (most commits are single-file)
first_file=$(echo "$files" | head -n1)

# Map file to description (simplified - we'll use a lookup)
case "$first_file" in
    "DeathCounterInstaller.exe")
        echo "Latest installer executable (v1.5). This is the main file users should download. Uses Git LFS for large file storage. Includes Python version compatibility checking and automatic Japanese language pack download for Sekiro support."
        ;;
    "README.md")
        echo "This documentation file. Contains installation instructions, feature descriptions, repository structure, and troubleshooting information."
        ;;
    ".gitattributes")
        echo "Git LFS configuration file. It tells Git which large files (e.g., \`*.exe\`) should be tracked by Git Large File Storage instead of directly in the Git repository. This prevents repository bloat and allows for easier management of large binaries."
        ;;
    ".gitignore")
        echo "Git ignore rules. This file specifies intentionally untracked files that Git should ignore (e.g., temporary files, build artifacts, local configurations). It helps keep the repository clean and focused on source code."
        ;;
    "cleanup_github_repo.ps1")
        echo "Utility PowerShell script used to organize the repository structure, remove old files, and copy the desired folder layout from a local reference folder. Helps maintain consistency between local development and GitHub repository."
        ;;
    "create_release.ps1")
        echo "PowerShell script for creating GitHub releases. Can be used to automate the process of creating a new release with the installer executable as a downloadable asset."
        ;;
    "All Contents/multi_game_death_counter.py")
        echo "Main daemon script that performs screen capture, OCR detection, and death counting"
        ;;
    "All Contents/death_counter_gui.py")
        echo "GUI application for controlling the daemon and viewing death statistics"
        ;;
    "All Contents/games_config.json")
        echo "Configuration file defining game-specific settings (capture regions, keywords, process names)"
        ;;
    *)
        # For other files, try to match pattern
        if echo "$first_file" | grep -q "^All Contents/"; then
            filename=$(basename "$first_file")
            case "$filename" in
                *.py) echo "Python script in All Contents folder: $(basename "$filename" .py)" ;;
                *.bat) echo "Batch file in All Contents folder: $(basename "$filename" .bat)" ;;
                *.json) echo "Configuration file in All Contents folder: $(basename "$filename" .json)" ;;
                *.txt) echo "Text file in All Contents folder: $(basename "$filename" .txt)" ;;
                *.cs) echo "C# file in All Contents folder: $(basename "$filename" .cs)" ;;
                *) echo "File in All Contents folder: $filename" ;;
            esac
        elif echo "$first_file" | grep -q "^Debug.Test/"; then
            filename=$(basename "$first_file")
            case "$filename" in
                *.py) echo "Debug and testing utility: $(basename "$filename" .py)" ;;
                *.bat) echo "Debug and testing batch file: $(basename "$filename" .bat)" ;;
                *) echo "Debug and testing file: $filename" ;;
            esac
        elif echo "$first_file" | grep -q "^Edit/"; then
            filename=$(basename "$first_file")
            case "$filename" in
                build_single_file.py) echo "Build script that packages all application files into a single installer script. This script embeds all necessary files (Python scripts, configs, batch files) into DeathCounter_Installer_Standalone.py." ;;
                DeathCounter_Installer_Standalone.py) echo "The standalone installer script generated by build_single_file.py. This is the Python script version of the installer before it's compiled into an .exe using PyInstaller." ;;
                *.py) echo "Development script: $(basename "$filename" .py)" ;;
                *.bat) echo "Development batch file: $(basename "$filename" .bat)" ;;
                *.json) echo "Development configuration file: $(basename "$filename" .json)" ;;
                *.cs) echo "Development C# file: $(basename "$filename" .cs)" ;;
                *) echo "Development file: $filename" ;;
            esac
        else
            # Keep original message for unrecognized files
            echo "$commit_msg"
        fi
        ;;
esac
'@

# Write the filter script to a temporary file
$filterScriptPath = Join-Path $PWD "git-msg-filter.sh"
Set-Content -Path $filterScriptPath -Value $filterScript -Encoding UTF8

Write-Host "Running git filter-branch to update all commit messages..."
Write-Host "This may take a few minutes..."
Write-Host ""

# Run filter-branch
$env:FILTER_BRANCH_SQUELCH_WARNING = "1"
git filter-branch -f --msg-filter "bash `"$filterScriptPath`"" HEAD

Write-Host ""
Write-Host "Done! Commit messages have been updated."
Write-Host "Review with: git log --oneline"
Write-Host "If satisfied, force push with: git push origin main --force"

# Clean up
Remove-Item $filterScriptPath -ErrorAction SilentlyContinue
